[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[build]
# This can cause weirdness if they don't match!
rustflags = ["-Ctarget-cpu=native"]
rustdocflags = ["-Ctarget-cpu=native"]
